// Generated from original source metadata by generate-fixtures.mjs; no web world coordinates.
using System.Collections.Generic;

namespace Gamesim.Simulation
{
    public static class WebNpcActivityCatalog
    {
        public static List<WebNpcActivityPoint> Points => new List<WebNpcActivityPoint>
        {
            new WebNpcActivityPoint { id = "sofa-seat-1", label = "Sofa Seat 1", room = "living", activity = "sit", capacity = 1, satisfaction = new List<WebNpcMotiveAmount> { new WebNpcMotiveAmount { motive = "social", amount = 4d }, new WebNpcMotiveAmount { motive = "rest", amount = 4d }, new WebNpcMotiveAmount { motive = "fun", amount = 3d } } },
            new WebNpcActivityPoint { id = "sofa-seat-2", label = "Sofa Seat 2", room = "living", activity = "sit", capacity = 1, satisfaction = new List<WebNpcMotiveAmount> { new WebNpcMotiveAmount { motive = "social", amount = 4d }, new WebNpcMotiveAmount { motive = "rest", amount = 4d }, new WebNpcMotiveAmount { motive = "fun", amount = 3d } } },
            new WebNpcActivityPoint { id = "sofa-seat-3", label = "Sofa Seat 3", room = "living", activity = "sit", capacity = 1, satisfaction = new List<WebNpcMotiveAmount> { new WebNpcMotiveAmount { motive = "social", amount = 4d }, new WebNpcMotiveAmount { motive = "rest", amount = 4d }, new WebNpcMotiveAmount { motive = "fun", amount = 3d } } },
            new WebNpcActivityPoint { id = "accent-chair-1", label = "Accent Chair 1", room = "living", activity = "sit", capacity = 1, satisfaction = new List<WebNpcMotiveAmount> { new WebNpcMotiveAmount { motive = "social", amount = 3d }, new WebNpcMotiveAmount { motive = "rest", amount = 4d }, new WebNpcMotiveAmount { motive = "fun", amount = 3d } } },
            new WebNpcActivityPoint { id = "accent-chair-2", label = "Accent Chair 2", room = "living", activity = "sit", capacity = 1, satisfaction = new List<WebNpcMotiveAmount> { new WebNpcMotiveAmount { motive = "social", amount = 3d }, new WebNpcMotiveAmount { motive = "rest", amount = 4d }, new WebNpcMotiveAmount { motive = "fun", amount = 3d } } },
            new WebNpcActivityPoint { id = "tv-area", label = "TV Area", room = "living", activity = "stand", capacity = 2, satisfaction = new List<WebNpcMotiveAmount> { new WebNpcMotiveAmount { motive = "social", amount = 2d }, new WebNpcMotiveAmount { motive = "energy", amount = 2d }, new WebNpcMotiveAmount { motive = "fun", amount = 4d } } },
            new WebNpcActivityPoint { id = "living-center", label = "Living Room Center", room = "living", activity = "stand", capacity = 2, satisfaction = new List<WebNpcMotiveAmount> { new WebNpcMotiveAmount { motive = "social", amount = 4d }, new WebNpcMotiveAmount { motive = "energy", amount = 2d } } },
            new WebNpcActivityPoint { id = "memory-wall", label = "Memory Wall", room = "living", activity = "stand", capacity = 2, satisfaction = new List<WebNpcMotiveAmount> { new WebNpcMotiveAmount { motive = "social", amount = 2d }, new WebNpcMotiveAmount { motive = "energy", amount = 2d } } },
            new WebNpcActivityPoint { id = "living-bookshelf", label = "Bookshelf Nook", room = "living", activity = "stand", capacity = 1, satisfaction = new List<WebNpcMotiveAmount> { new WebNpcMotiveAmount { motive = "social", amount = 2d }, new WebNpcMotiveAmount { motive = "energy", amount = 2d }, new WebNpcMotiveAmount { motive = "fun", amount = 5d }, new WebNpcMotiveAmount { motive = "rest", amount = 4d } } },
            new WebNpcActivityPoint { id = "dining-chair-1", label = "Dining Chair 1", room = "kitchen", activity = "sit", capacity = 1, satisfaction = new List<WebNpcMotiveAmount> { new WebNpcMotiveAmount { motive = "social", amount = 5d }, new WebNpcMotiveAmount { motive = "rest", amount = 3d }, new WebNpcMotiveAmount { motive = "fun", amount = 2d }, new WebNpcMotiveAmount { motive = "energy", amount = 6d } } },
            new WebNpcActivityPoint { id = "dining-chair-2", label = "Dining Chair 2", room = "kitchen", activity = "sit", capacity = 1, satisfaction = new List<WebNpcMotiveAmount> { new WebNpcMotiveAmount { motive = "social", amount = 5d }, new WebNpcMotiveAmount { motive = "rest", amount = 3d }, new WebNpcMotiveAmount { motive = "fun", amount = 2d }, new WebNpcMotiveAmount { motive = "energy", amount = 6d } } },
            new WebNpcActivityPoint { id = "dining-chair-4", label = "Dining Chair 4", room = "kitchen", activity = "sit", capacity = 1, satisfaction = new List<WebNpcMotiveAmount> { new WebNpcMotiveAmount { motive = "social", amount = 5d }, new WebNpcMotiveAmount { motive = "rest", amount = 3d }, new WebNpcMotiveAmount { motive = "fun", amount = 2d }, new WebNpcMotiveAmount { motive = "energy", amount = 6d } } },
            new WebNpcActivityPoint { id = "island-stool-1", label = "Island Stool 1", room = "kitchen", activity = "sit", capacity = 1, satisfaction = new List<WebNpcMotiveAmount> { new WebNpcMotiveAmount { motive = "social", amount = 4d }, new WebNpcMotiveAmount { motive = "rest", amount = 3d }, new WebNpcMotiveAmount { motive = "fun", amount = 2d }, new WebNpcMotiveAmount { motive = "energy", amount = 5d } } },
            new WebNpcActivityPoint { id = "island-stool-2", label = "Island Stool 2", room = "kitchen", activity = "sit", capacity = 1, satisfaction = new List<WebNpcMotiveAmount> { new WebNpcMotiveAmount { motive = "social", amount = 4d }, new WebNpcMotiveAmount { motive = "rest", amount = 3d }, new WebNpcMotiveAmount { motive = "fun", amount = 2d }, new WebNpcMotiveAmount { motive = "energy", amount = 5d } } },
            new WebNpcActivityPoint { id = "island-stool-3", label = "Island Stool 3", room = "kitchen", activity = "sit", capacity = 1, satisfaction = new List<WebNpcMotiveAmount> { new WebNpcMotiveAmount { motive = "social", amount = 4d }, new WebNpcMotiveAmount { motive = "rest", amount = 3d }, new WebNpcMotiveAmount { motive = "fun", amount = 2d }, new WebNpcMotiveAmount { motive = "energy", amount = 5d } } },
            new WebNpcActivityPoint { id = "kitchen-island", label = "Kitchen Island", room = "kitchen", activity = "cook", capacity = 1, satisfaction = new List<WebNpcMotiveAmount> { new WebNpcMotiveAmount { motive = "energy", amount = 4d }, new WebNpcMotiveAmount { motive = "social", amount = 2d } } },
            new WebNpcActivityPoint { id = "kitchen-counter", label = "Kitchen Counter", room = "kitchen", activity = "cook", capacity = 1, satisfaction = new List<WebNpcMotiveAmount> { new WebNpcMotiveAmount { motive = "energy", amount = 4d }, new WebNpcMotiveAmount { motive = "social", amount = 2d } } },
            new WebNpcActivityPoint { id = "kitchen-stand", label = "Kitchen Entrance", room = "kitchen", activity = "stand", capacity = 2, satisfaction = new List<WebNpcMotiveAmount> { new WebNpcMotiveAmount { motive = "social", amount = 3d }, new WebNpcMotiveAmount { motive = "energy", amount = 2d } } },
            new WebNpcActivityPoint { id = "kitchen-snack", label = "Snack Bar", room = "kitchen", activity = "eat", capacity = 1, satisfaction = new List<WebNpcMotiveAmount> { new WebNpcMotiveAmount { motive = "energy", amount = 6d }, new WebNpcMotiveAmount { motive = "fun", amount = 2d } } },
            new WebNpcActivityPoint { id = "bed-1", label = "Bed 1", room = "bedroom", activity = "sleep", capacity = 1, satisfaction = new List<WebNpcMotiveAmount> { new WebNpcMotiveAmount { motive = "rest", amount = 10d } } },
            new WebNpcActivityPoint { id = "bed-2", label = "Bed 2", room = "bedroom", activity = "sleep", capacity = 1, satisfaction = new List<WebNpcMotiveAmount> { new WebNpcMotiveAmount { motive = "rest", amount = 10d } } },
            new WebNpcActivityPoint { id = "bedroom-stand", label = "Bedroom Standing", room = "bedroom", activity = "stand", capacity = 2, satisfaction = new List<WebNpcMotiveAmount> { new WebNpcMotiveAmount { motive = "social", amount = 3d }, new WebNpcMotiveAmount { motive = "energy", amount = 2d } } },
            new WebNpcActivityPoint { id = "bedroom-chat", label = "Bed Edge Chat", room = "bedroom", activity = "stand", capacity = 2, satisfaction = new List<WebNpcMotiveAmount> { new WebNpcMotiveAmount { motive = "social", amount = 6d }, new WebNpcMotiveAmount { motive = "energy", amount = 2d }, new WebNpcMotiveAmount { motive = "rest", amount = 3d } } },
            new WebNpcActivityPoint { id = "havenot-bed-1", label = "Have-Not Bed 1", room = "havenot", activity = "sleep", capacity = 1, satisfaction = new List<WebNpcMotiveAmount> { new WebNpcMotiveAmount { motive = "rest", amount = 10d } } },
            new WebNpcActivityPoint { id = "havenot-bed-2", label = "Have-Not Bed 2", room = "havenot", activity = "sleep", capacity = 1, satisfaction = new List<WebNpcMotiveAmount> { new WebNpcMotiveAmount { motive = "rest", amount = 10d } } },
            new WebNpcActivityPoint { id = "hoh-bed", label = "HOH Bed", room = "hoh", activity = "sleep", capacity = 1, satisfaction = new List<WebNpcMotiveAmount> { new WebNpcMotiveAmount { motive = "rest", amount = 10d } } },
            new WebNpcActivityPoint { id = "hoh-lounge", label = "HOH Lounge Chair", room = "hoh", activity = "sit", capacity = 1, satisfaction = new List<WebNpcMotiveAmount> { new WebNpcMotiveAmount { motive = "social", amount = 3d }, new WebNpcMotiveAmount { motive = "rest", amount = 5d }, new WebNpcMotiveAmount { motive = "fun", amount = 3d } } },
            new WebNpcActivityPoint { id = "nom-seat-1", label = "Nomination Seat Left", room = "nomination", activity = "sit", capacity = 1, satisfaction = new List<WebNpcMotiveAmount> { new WebNpcMotiveAmount { motive = "social", amount = 5d }, new WebNpcMotiveAmount { motive = "rest", amount = 3d }, new WebNpcMotiveAmount { motive = "fun", amount = 2d } } },
            new WebNpcActivityPoint { id = "nom-seat-2", label = "Nomination Seat Center", room = "nomination", activity = "sit", capacity = 1, satisfaction = new List<WebNpcMotiveAmount> { new WebNpcMotiveAmount { motive = "social", amount = 5d }, new WebNpcMotiveAmount { motive = "rest", amount = 3d }, new WebNpcMotiveAmount { motive = "fun", amount = 2d } } },
            new WebNpcActivityPoint { id = "nom-seat-3", label = "Nomination Seat Right", room = "nomination", activity = "sit", capacity = 1, satisfaction = new List<WebNpcMotiveAmount> { new WebNpcMotiveAmount { motive = "social", amount = 5d }, new WebNpcMotiveAmount { motive = "rest", amount = 3d }, new WebNpcMotiveAmount { motive = "fun", amount = 2d } } },
            new WebNpcActivityPoint { id = "nom-center", label = "Nomination Area", room = "nomination", activity = "stand", capacity = 2, satisfaction = new List<WebNpcMotiveAmount> { new WebNpcMotiveAmount { motive = "social", amount = 2d }, new WebNpcMotiveAmount { motive = "energy", amount = 2d } } },
            new WebNpcActivityPoint { id = "pool-table-1", label = "Pool Table Left", room = "game", activity = "game", capacity = 1, satisfaction = new List<WebNpcMotiveAmount> { new WebNpcMotiveAmount { motive = "fun", amount = 6d }, new WebNpcMotiveAmount { motive = "social", amount = 3d } } },
            new WebNpcActivityPoint { id = "arcade-cabinet", label = "Arcade Cabinet", room = "game", activity = "game", capacity = 1, satisfaction = new List<WebNpcMotiveAmount> { new WebNpcMotiveAmount { motive = "fun", amount = 7d }, new WebNpcMotiveAmount { motive = "social", amount = 2d } } },
            new WebNpcActivityPoint { id = "pool-table-2", label = "Pool Table Right", room = "game", activity = "game", capacity = 1, satisfaction = new List<WebNpcMotiveAmount> { new WebNpcMotiveAmount { motive = "fun", amount = 6d }, new WebNpcMotiveAmount { motive = "social", amount = 3d } } },
            new WebNpcActivityPoint { id = "game-lounge-1", label = "Game Lounge Seat 1", room = "game", activity = "sit", capacity = 1, satisfaction = new List<WebNpcMotiveAmount> { new WebNpcMotiveAmount { motive = "social", amount = 4d }, new WebNpcMotiveAmount { motive = "rest", amount = 3d }, new WebNpcMotiveAmount { motive = "fun", amount = 5d } } },
            new WebNpcActivityPoint { id = "game-lounge-2", label = "Game Lounge Seat 2", room = "game", activity = "sit", capacity = 1, satisfaction = new List<WebNpcMotiveAmount> { new WebNpcMotiveAmount { motive = "social", amount = 4d }, new WebNpcMotiveAmount { motive = "rest", amount = 3d }, new WebNpcMotiveAmount { motive = "fun", amount = 5d } } },
            new WebNpcActivityPoint { id = "game-darts", label = "Dartboard", room = "game", activity = "game", capacity = 2, satisfaction = new List<WebNpcMotiveAmount> { new WebNpcMotiveAmount { motive = "fun", amount = 7d }, new WebNpcMotiveAmount { motive = "social", amount = 4d } } },
            new WebNpcActivityPoint { id = "bathroom-mirror", label = "Bathroom Mirror", room = "bathroom", activity = "groom", capacity = 1, satisfaction = new List<WebNpcMotiveAmount> { new WebNpcMotiveAmount { motive = "hygiene", amount = 10d } } },
            new WebNpcActivityPoint { id = "bathroom-stand", label = "Bathroom Standing", room = "bathroom", activity = "stand", capacity = 1, satisfaction = new List<WebNpcMotiveAmount> { new WebNpcMotiveAmount { motive = "social", amount = 2d }, new WebNpcMotiveAmount { motive = "energy", amount = 2d } } },
            new WebNpcActivityPoint { id = "fire-pit", label = "Fire Pit", room = "backyard", activity = "sit", capacity = 2, satisfaction = new List<WebNpcMotiveAmount> { new WebNpcMotiveAmount { motive = "social", amount = 5d }, new WebNpcMotiveAmount { motive = "rest", amount = 3d }, new WebNpcMotiveAmount { motive = "fun", amount = 3d } } },
            new WebNpcActivityPoint { id = "hot-tub", label = "Hot Tub", room = "backyard", activity = "swim", capacity = 2, satisfaction = new List<WebNpcMotiveAmount> { new WebNpcMotiveAmount { motive = "fun", amount = 7d }, new WebNpcMotiveAmount { motive = "hygiene", amount = 3d }, new WebNpcMotiveAmount { motive = "social", amount = 3d }, new WebNpcMotiveAmount { motive = "rest", amount = 4d } } },
            new WebNpcActivityPoint { id = "hammock", label = "Hammock", room = "backyard", activity = "lounge", capacity = 1, satisfaction = new List<WebNpcMotiveAmount> { new WebNpcMotiveAmount { motive = "rest", amount = 5d }, new WebNpcMotiveAmount { motive = "fun", amount = 4d }, new WebNpcMotiveAmount { motive = "energy", amount = 3d } } },
            new WebNpcActivityPoint { id = "patio-table", label = "Patio Table", room = "backyard", activity = "sit", capacity = 2, satisfaction = new List<WebNpcMotiveAmount> { new WebNpcMotiveAmount { motive = "social", amount = 4d }, new WebNpcMotiveAmount { motive = "rest", amount = 3d }, new WebNpcMotiveAmount { motive = "fun", amount = 2d }, new WebNpcMotiveAmount { motive = "energy", amount = 3d } } },
            new WebNpcActivityPoint { id = "pool-lounge-3", label = "Pool Lounger", room = "backyard", activity = "lounge", capacity = 1, satisfaction = new List<WebNpcMotiveAmount> { new WebNpcMotiveAmount { motive = "rest", amount = 6d }, new WebNpcMotiveAmount { motive = "fun", amount = 4d } } },
            new WebNpcActivityPoint { id = "backyard-stand", label = "Backyard Standing", room = "backyard", activity = "stand", capacity = 2, satisfaction = new List<WebNpcMotiveAmount> { new WebNpcMotiveAmount { motive = "social", amount = 3d }, new WebNpcMotiveAmount { motive = "energy", amount = 2d }, new WebNpcMotiveAmount { motive = "fun", amount = 2d } } },
            new WebNpcActivityPoint { id = "bbq-grill", label = "BBQ Grill", room = "backyard", activity = "cook", capacity = 1, satisfaction = new List<WebNpcMotiveAmount> { new WebNpcMotiveAmount { motive = "energy", amount = 6d }, new WebNpcMotiveAmount { motive = "social", amount = 2d }, new WebNpcMotiveAmount { motive = "fun", amount = 3d } } },
            new WebNpcActivityPoint { id = "outdoor-seating", label = "Outdoor Seating", room = "backyard", activity = "sit", capacity = 2, satisfaction = new List<WebNpcMotiveAmount> { new WebNpcMotiveAmount { motive = "social", amount = 3d }, new WebNpcMotiveAmount { motive = "rest", amount = 2d }, new WebNpcMotiveAmount { motive = "fun", amount = 2d } } },
            new WebNpcActivityPoint { id = "pool-diving-board", label = "Pool Diving Board", room = "backyard", activity = "swim", capacity = 1, satisfaction = new List<WebNpcMotiveAmount> { new WebNpcMotiveAmount { motive = "fun", amount = 5d }, new WebNpcMotiveAmount { motive = "hygiene", amount = 3d }, new WebNpcMotiveAmount { motive = "social", amount = 3d }, new WebNpcMotiveAmount { motive = "energy", amount = -2d } } },
            new WebNpcActivityPoint { id = "garden-bench", label = "Garden Bench", room = "backyard", activity = "sit", capacity = 2, satisfaction = new List<WebNpcMotiveAmount> { new WebNpcMotiveAmount { motive = "social", amount = 4d }, new WebNpcMotiveAmount { motive = "rest", amount = 3d }, new WebNpcMotiveAmount { motive = "fun", amount = 2d } } },
            new WebNpcActivityPoint { id = "outdoor-bar", label = "Outdoor Bar Counter", room = "backyard", activity = "stand", capacity = 1, satisfaction = new List<WebNpcMotiveAmount> { new WebNpcMotiveAmount { motive = "social", amount = 5d }, new WebNpcMotiveAmount { motive = "energy", amount = 2d }, new WebNpcMotiveAmount { motive = "fun", amount = 3d } } },
            new WebNpcActivityPoint { id = "hallway-center", label = "Hallway Center", room = "hallway", activity = "stand", capacity = 2, satisfaction = new List<WebNpcMotiveAmount> { new WebNpcMotiveAmount { motive = "social", amount = 2d }, new WebNpcMotiveAmount { motive = "energy", amount = 2d } } },
            new WebNpcActivityPoint { id = "hallway-left", label = "Hallway Left", room = "hallway", activity = "stand", capacity = 2, satisfaction = new List<WebNpcMotiveAmount> { new WebNpcMotiveAmount { motive = "social", amount = 2d }, new WebNpcMotiveAmount { motive = "energy", amount = 2d } } },
            new WebNpcActivityPoint { id = "hallway-right", label = "Hallway Right", room = "hallway", activity = "stand", capacity = 2, satisfaction = new List<WebNpcMotiveAmount> { new WebNpcMotiveAmount { motive = "social", amount = 2d }, new WebNpcMotiveAmount { motive = "energy", amount = 2d } } },
            new WebNpcActivityPoint { id = "diary-chair", label = "Diary Room Chair", room = "diary", activity = "sit", capacity = 1, satisfaction = new List<WebNpcMotiveAmount> { new WebNpcMotiveAmount { motive = "social", amount = -2d }, new WebNpcMotiveAmount { motive = "rest", amount = 3d }, new WebNpcMotiveAmount { motive = "fun", amount = 2d } } },
            new WebNpcActivityPoint { id = "hoh-desk", label = "HOH Desk", room = "hoh", activity = "stand", capacity = 1, satisfaction = new List<WebNpcMotiveAmount> { new WebNpcMotiveAmount { motive = "social", amount = 2d }, new WebNpcMotiveAmount { motive = "energy", amount = 2d }, new WebNpcMotiveAmount { motive = "fun", amount = 4d }, new WebNpcMotiveAmount { motive = "rest", amount = 2d } } },
            new WebNpcActivityPoint { id = "havenot-stand", label = "Have-Not Standing", room = "havenot", activity = "stand", capacity = 2, satisfaction = new List<WebNpcMotiveAmount> { new WebNpcMotiveAmount { motive = "social", amount = 3d }, new WebNpcMotiveAmount { motive = "energy", amount = 2d } } },
            new WebNpcActivityPoint { id = "fridge-eat", label = "Fridge", room = "kitchen", activity = "eat", capacity = 1, satisfaction = new List<WebNpcMotiveAmount> { new WebNpcMotiveAmount { motive = "energy", amount = 5d }, new WebNpcMotiveAmount { motive = "fun", amount = 3d } } },
            new WebNpcActivityPoint { id = "shower-clean-l", label = "Shower Left", room = "bathroom", activity = "clean", capacity = 1, satisfaction = new List<WebNpcMotiveAmount> { new WebNpcMotiveAmount { motive = "hygiene", amount = 6d } } },
            new WebNpcActivityPoint { id = "shower-clean-r", label = "Shower Right", room = "bathroom", activity = "clean", capacity = 1, satisfaction = new List<WebNpcMotiveAmount> { new WebNpcMotiveAmount { motive = "hygiene", amount = 6d } } },
            new WebNpcActivityPoint { id = "tv-watch", label = "TV Watching", room = "living", activity = "stand", capacity = 2, satisfaction = new List<WebNpcMotiveAmount> { new WebNpcMotiveAmount { motive = "social", amount = 3d }, new WebNpcMotiveAmount { motive = "energy", amount = 2d }, new WebNpcMotiveAmount { motive = "fun", amount = 6d }, new WebNpcMotiveAmount { motive = "rest", amount = 4d } } },
            new WebNpcActivityPoint { id = "backyard-exercise", label = "Exercise Area", room = "backyard", activity = "exercise", capacity = 2, satisfaction = new List<WebNpcMotiveAmount> { new WebNpcMotiveAmount { motive = "energy", amount = -3d }, new WebNpcMotiveAmount { motive = "fun", amount = 4d } } },
        };
        public static List<WebNpcActivityPhase> Phases => new List<WebNpcActivityPhase>
        {
            new WebNpcActivityPhase { activity = "sit", startDuration = 800, endDuration = 600, startGesture = null, endGesture = null, pickUpItem = null, putDownItem = false },
            new WebNpcActivityPhase { activity = "stand", startDuration = 300, endDuration = 300, startGesture = null, endGesture = null, pickUpItem = null, putDownItem = false },
            new WebNpcActivityPhase { activity = "cook", startDuration = 1200, endDuration = 1000, startGesture = "armStretch", endGesture = "handCheck", pickUpItem = "plate", putDownItem = true },
            new WebNpcActivityPhase { activity = "sleep", startDuration = 1500, endDuration = 2000, startGesture = "microYawn", endGesture = "microStretch", pickUpItem = null, putDownItem = false },
            new WebNpcActivityPhase { activity = "game", startDuration = 600, endDuration = 500, startGesture = "shoulderRoll", endGesture = null, pickUpItem = null, putDownItem = false },
            new WebNpcActivityPhase { activity = "groom", startDuration = 800, endDuration = 600, startGesture = null, endGesture = "handCheck", pickUpItem = "towel", putDownItem = true },
            new WebNpcActivityPhase { activity = "lounge", startDuration = 1000, endDuration = 800, startGesture = "microStretch", endGesture = null, pickUpItem = null, putDownItem = false },
            new WebNpcActivityPhase { activity = "swim", startDuration = 1200, endDuration = 1000, startGesture = "armStretch", endGesture = null, pickUpItem = "towel", putDownItem = false },
            new WebNpcActivityPhase { activity = "eat", startDuration = 600, endDuration = 500, startGesture = null, endGesture = null, pickUpItem = null, putDownItem = false },
            new WebNpcActivityPhase { activity = "clean", startDuration = 800, endDuration = 600, startGesture = "armStretch", endGesture = null, pickUpItem = "towel", putDownItem = true },
            new WebNpcActivityPhase { activity = "watch_tv", startDuration = 500, endDuration = 400, startGesture = null, endGesture = null, pickUpItem = null, putDownItem = false },
            new WebNpcActivityPhase { activity = "exercise", startDuration = 1000, endDuration = 800, startGesture = "armStretch", endGesture = null, pickUpItem = null, putDownItem = false },
        };
        public static List<WebNpcChainMetadata> Chains => new List<WebNpcChainMetadata>
        {
            new WebNpcChainMetadata { id = "morning", carryItem = null, steps = new List<string> { "sleep", "groom", "cook" } },
            new WebNpcChainMetadata { id = "refresh", carryItem = null, steps = new List<string> { "swim", "groom", "lounge" } },
            new WebNpcChainMetadata { id = "social_loop", carryItem = null, steps = new List<string> { "stand", "sit", "stand" } },
            new WebNpcChainMetadata { id = "game_break", carryItem = null, steps = new List<string> { "game", "sit", "game" } },
            new WebNpcChainMetadata { id = "wind_down", carryItem = null, steps = new List<string> { "lounge", "groom", "sleep" } },
            new WebNpcChainMetadata { id = "cook_eat", carryItem = "plate", steps = new List<string> { "cook", "sit" } },
            new WebNpcChainMetadata { id = "cook_eat_cleanup", carryItem = "plate", steps = new List<string> { "cook", "sit", "stand" } },
            new WebNpcChainMetadata { id = "swim_groom", carryItem = "towel", steps = new List<string> { "swim", "groom" } },
        };
        public static List<WebNpcCarryChain> CarryChains => new List<WebNpcCarryChain>
        {
            new WebNpcCarryChain { activity = "cook", item = "plate", targetActivity = "sit", targetRoom = "kitchen" },
            new WebNpcCarryChain { activity = "groom", item = "towel", targetActivity = "sleep", targetRoom = "bedroom" },
        };
    }
}
